### ISSUE TITLE
Missing Dependencies?

### ISSUE THREAD

**Issue by frequencydesign** [mairatma/metal-jsx-modal#1]
Hello, using a Cloud9 Environment, I was able to get this running using all the following commands:
:~/workspace $ git clone https://github.com/mairatma/metal-jsx-modal.git workspace
:~/workspace $ npm install -g gulp
:~/workspace $ npm install
:~/workspace $ gulp build
:~/workspace $ npm install metal-component
:~/workspace $ npm install metal-incremental-dom
:~/workspace $ npm install metal
:~/workspace $ gulp build
:~/workspace $ npm install metal-dom
:~/workspace $ npm install metal-events
:~/workspace $ npm install metal-state
:~/workspace $ gulp build

Is there a place where we could include those other required dependencies in order to get this to work like in the README directions?

Also, I tried this on a Windows machine with too many dependency failures to resolve. Have you had any Windows developers successfully run this?  Thanks.

**Comment by mairatma** [comment]
You're probably using **npm <  3.0.0**, which would cause these dependency problems you've mentioned. We've decided to fix on **npm >= 3.0.0** for Metal.js, you can see that on this project's [package.json](https://github.com/mairatma/metal-jsx-modal/blob/master/package.json#L9). You're right that the README directions should make this clear though. The global `gulp` dependency is already explained there, but not the npm version.

And no, I don't think we've tried this on windows recently, so it's possible that there are problems with it. I'll investigate, thanks for the heads up!

**Comment by frequencydesign** [comment]
You are spot on about npm and thanks for the response. On my Windows machine I'm running 3.7.2 and no, it's not able to work on windows at this point.

I was using cloud9 for the first example and didn't realize they default to npm 2.14.20 - after updating to 3.8.6 with npm i -g npm, I was able to follow your README exactly and get it working. Thanks!
